# Registration Functionality
link_registration="//a[normalize-space()='Register']"
rdo_btn_gender_male="//input[@id='gender-male']"
txt_firstname="//input[@id='FirstName']"
txt_lastname="//input[@id='LastName']"
txt_email="//input[@id='Email']"
txt_password="//input[@id='Password']"
txt_confirm_password="//input[@id='ConfirmPassword']"
btn_register="//button[@id='register-button']"
successful_message="//div[normalize-space()='Your registration completed']"
btn_continue="//a[normalize-space()='Continue']"
txt_myaccount="//a[@class='ico-account']"
dd_day="//select[@name='DateOfBirthDay']"
txt_company_name="//input[@id='Company']"
txt_newsletter="//input[@id='Newsletter']"
link_login="//a[normalize-space()='Log in']"
confim_login_text="//h1[normalize-space()='Welcome, Please Sign In!']"
btn_register_on_login="//button[normalize-space()='Register']"
registration_txt="//h1[normalize-space()='Register']"
warning_firstname="//span[@id='FirstName-error']"
warning_lastname="//span[@id='LastName-error']"
warning_email="//span[@id='Email-error']"
warning_password="//span[@id='Password-error']"
warning_confirm_password="//span[@id='ConfirmPassword-error']"
warning_pass_not_matched="//span[@id='ConfirmPassword-error']"
warning_exist_email="//li[normalize-space()='The specified email already exists']"
warning_wrong_email="//span[@id='Email-error']"
red_asterisk="//span[@class='required' and contains(text(), '*')]"
all_mandatory_fields="//input[contains(@id,'Name') or @id='Email' or @type='password']"